In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df_test = pd.read_csv('test.csv')
df_train = pd.read_csv('train.csv')

In [3]:
df_test.head()

id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0   1           1043     1          1.8         1  14       0           5   
1   2            841     1          0.5         1   4       1          61   
2   3           1807     1          2.8         0   1       0          27   
3   4           1546     0          0.5         1  18       1          25   
4   5           1434     0          1.4         0  11       1          49   

   m_dep  mobile_wt  ...  pc  px_height  px_width   ram  sc_h  sc_w  \
0    0.1        193  ...  16        226      1412  3476    12     7   
1    0.8        191  ...  12        746       857  3895     6     0   
2    0.9        186  ...   4       1270      1366  2396    17    10   
3    0.5         96  ...  20        295      1752  3893    10     0   
4    0.5        108  ...  18        749       810  1773    15     8   

   talk_time  three_g  touch_screen  wifi  
0          2        0             1     0  
1          7        1             0     0  
2         10        0             1     1  
3          7        1             1     0  
4          7        1             0     1  

[5 rows x 21 columns]

In [7]:
df_train.columns.tolist()

['battery_power',
 'blue',
 'clock_speed',
 'dual_sim',
 'fc',
 'four_g',
 'int_memory',
 'm_dep',
 'mobile_wt',
 'n_cores',
 'pc',
 'px_height',
 'px_width',
 'ram',
 'sc_h',
 'sc_w',
 'talk_time',
 'three_g',
 'touch_screen',
 'wifi',
 'price_range']

In [13]:
X_train = df_train.drop('price_range', axis=1)
y_train = df_train['price_range']

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size = 0.2, random_state = 42)

In [31]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=42)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=42)

In [34]:
y_pred = classifier.predict(X_val)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_val.to_numpy().reshape(len(y_val),1)), 1))

[[3 3]
 [2 2]
 [0 0]
 [1 1]
 [0 0]
 [2 3]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [1 0]
 [3 3]
 [3 3]
 [2 3]
 [0 0]
 [0 0]
 [1 0]
 [2 2]
 [2 3]
 [1 1]
 [2 2]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [3 3]
 [0 0]
 [0 0]
 [1 1]
 [1 2]
 [0 0]
 [2 3]
 [3 3]
 [3 3]
 [0 0]
 [1 1]
 [1 0]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [1 2]
 [0 0]
 [1 1]
 [1 2]
 [3 3]
 [3 3]
 [3 3]
 [0 0]
 [3 3]
 [0 0]
 [0 0]
 [0 0]
 [3 3]
 [3 3]
 [0 0]
 [0 0]
 [2 2]
 [2 2]
 [1 0]
 [3 3]
 [3 3]
 [3 2]
 [2 2]
 [0 0]
 [3 3]
 [1 1]
 [0 0]
 [1 1]
 [2 2]
 [0 0]
 [0 0]
 [2 2]
 [2 2]
 [1 1]
 [0 0]
 [3 3]
 [2 2]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [3 3]
 [1 1]
 [0 0]
 [3 3]
 [1 1]
 [2 1]
 [0 1]
 [1 1]
 [2 2]
 [3 3]
 [0 0]
 [3 3]
 [1 1]
 [3 3]
 [2 3]
 [3 3]
 [0 1]
 [2 2]
 [1 1]
 [2 2]
 [0 0]
 [2 2]
 [3 3]
 [3 3]
 [2 2]
 [2 2]
 [0 0]
 [1 2]
 [2 1]
 [0 0]
 [1 1]
 [2 2]
 [3 3]
 [0 0]
 [0 0]
 [3 3]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [1 1]
 [0 0]
 [2 2]
 [0 0]
 [1 1]
 [0 0]

In [37]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_val, y_pred)
accu_s = accuracy_score(y_val,y_pred)
print(cm) #65 right of who bought, and 24 right of doesnt bought
print(accu_s)
class_report = classification_report(y_val, y_pred)
print(class_report)

[[78  6  0  0]
 [ 4 67  2  0]
 [ 0  9 69  1]
 [ 0  0  8 76]]
0.90625
              precision    recall  f1-score   support

           0       0.95      0.93      0.94        84
           1       0.82      0.92      0.86        73
           2       0.87      0.87      0.87        79
           3       0.99      0.90      0.94        84

    accuracy                           0.91       320
   macro avg       0.91      0.91      0.91       320
weighted avg       0.91      0.91      0.91       320

